<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EstadoCivil;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * EstadoCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCivilRepository extends EntityRepository
{
    public function agregarEstadoCivil($data)
    {
        try {
            $em = $this->getEntityManager();
            $estadoCivil = new EstadoCivil();
            $this->saveEstadoCivil($estadoCivil,$data);

            $em->persist($estadoCivil);
            $em->flush();
            $msg = $estadoCivil;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El estado civil ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el estado civil';
            }
        }
        return $msg;
    }

    public function modificarEstadoCivil($data)
    {
        try {
            $em = $this->getEntityManager();
            $estadoCivil = $em->getRepository('AppBundle:EstadoCivil')->find($data['id']);

            if (!empty($estadoCivil)) {
                $this->saveEstadoCivil($estadoCivil,$data);

                $em->flush();
                $msg = $estadoCivil;
            } else {
                $msg = $estadoCivil;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el estado civil';
        }

        return $msg;
    }

    public function eliminarEstadoCivil($id)
    {
        try {
            $em = $this->getEntityManager();
            $estadoCivil = $em->getRepository('AppBundle:EstadoCivil')->find($id);

            if (!empty($estadoCivil)) {
                $em->remove($estadoCivil);
                $em->flush();
                $msg = $estadoCivil;
            } else {
                $msg = $estadoCivil;
            }

        } catch (Exception $e) {

            $msg = 'Se produjo un error al eliminar el estado civil';

        }
        return $msg;
    }

    private function saveEstadoCivil($estadoCivil,$data){
        $estadoCivil->setNombre($data['nombre']);
    }
}
