<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FactorRiesgo;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * FactorRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorRiesgoRepository extends EntityRepository
{
    public function agregarFactorRiesgo($data)
    {
        try {
            $em = $this->getEntityManager();
            $factorRiesgo = new FactorRiesgo();
            $this->saveFactorRiesgo($factorRiesgo,$data);

            $em->persist($factorRiesgo);
            $em->flush();
            $msg = $factorRiesgo;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El factor de riesgo ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el factor de riesgo';
            }
        }
        return $msg;
    }

    public function modificarFactorRiesgo($data)
    {
        try {
            $em = $this->getEntityManager();
            $factorRiesgo = $em->getRepository('AppBundle:FactorRiesgo')->find($data['id']);

            if (!empty($factorRiesgo)) {
                $this->saveFactorRiesgo($factorRiesgo,$data);

                $em->flush();
                $msg = $factorRiesgo;
            } else {
                $msg = $factorRiesgo;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el factor de riesgo';
        }

        return $msg;
    }

    public function eliminarFactorRiesgo($id)
    {
        try {
            $em = $this->getEntityManager();
            $factorRiesgo = $em->getRepository('AppBundle:FactorRiesgo')->find($id);

            if (!empty($factorRiesgo)) {
                $em->remove($factorRiesgo);
                $em->flush();
                $msg = $factorRiesgo;
            } else {
                $msg = $factorRiesgo;
            }

        } catch (Exception $e) {

            $msg = 'Se produjo un error al eliminar el factor de riesgo';

        }
        return $msg;
    }

    private function saveFactorRiesgo($factorRiesgo,$data){
        $factorRiesgo->setNombre($data['nombre']);
    }
}
