<?php

namespace AppBundle\Repository;

use AppBundle\Entity\GradoIndependencia;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * GradoIndependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradoIndependenciaRepository extends EntityRepository
{
    public function agregarGradoIndependencia($data)
    {
        try {
            $em = $this->getEntityManager();
            $gradoIndependencia = new GradoIndependencia();
            $this->saveGradoIndependencia($gradoIndependencia,$data);

            $em->persist($gradoIndependencia);
            $em->flush();
            $msg = $gradoIndependencia;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El grado de independencia ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el grado de independencia';
            }
        }
        return $msg;
    }

    public function modificarGradoIndependencia($data)
    {
        try {
            $em = $this->getEntityManager();
            $gradoIndependencia = $em->getRepository('AppBundle:GradoIndependencia')->find($data['id']);

            if (!empty($gradoIndependencia)) {
                $this->saveGradoIndependencia($gradoIndependencia,$data);

                $em->flush();
                $msg = $gradoIndependencia;
            } else {
                $msg = $gradoIndependencia;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el grado de independencia';
        }

        return $msg;
    }

    public function eliminarGradoIndependencia($id)
    {
        try {
            $em = $this->getEntityManager();
            $gradoIndependencia = $em->getRepository('AppBundle:GradoIndependencia')->find($id);

            if (!empty($gradoIndependencia)) {
                $em->remove($gradoIndependencia);
                $em->flush();
                $msg = $gradoIndependencia;
            } else {
                $msg = $gradoIndependencia;
            }

        } catch (Exception $e) {

            $msg = 'Se produjo un error al eliminar el grado de independencia';

        }
        return $msg;
    }

    private function saveGradoIndependencia($gradoIndependencia,$data){
        $gradoIndependencia->setNombre($data['nombre']);
    }
}
