<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profesion;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * ProfesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionRepository extends EntityRepository
{
    public function agregarProfesion($data)
    {
        try {
            $em = $this->getEntityManager();
            $profesion = new Profesion();
            $this->saveProfesion($profesion,$data);

            $em->persist($profesion);
            $em->flush();
            $msg = $profesion;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El profesión ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el profesión';
            }
        }
        return $msg;
    }

    public function modificarProfesion($data)
    {
        try {
            $em = $this->getEntityManager();
            $profesion = $em->getRepository('AppBundle:Profesion')->find($data['id']);

            if (!empty($profesion)) {
                $this->saveProfesion($profesion,$data);

                $em->flush();
                $msg = $profesion;
            } else {
                $msg = $profesion;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el profesión';
        }

        return $msg;
    }

    public function eliminarProfesion($id)
    {
        try {
            $em = $this->getEntityManager();
            $profesion = $em->getRepository('AppBundle:Profesion')->find($id);

            if (!empty($profesion)) {
                $em->remove($profesion);
                $em->flush();
                $msg = $profesion;
            } else {
                $msg = $profesion;
            }

        } catch (Exception $e) {

            $msg = 'Se produjo un error al eliminar el profesión';

        }
        return $msg;
    }

    private function saveProfesion($profesion,$data){
        $profesion->setNombre($data['nombre']);
    }
}
