<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoDominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDominioRepository extends EntityRepository
{
}
